__title__ = 'spacy_readability'
__version__ = '1.3.0'
__summary__ = 'spaCy pipeline component for adding text readability meta data to Doc objects.'
__uri__ = 'https://github.com/mholtzscher/spacy_readability'
__author__ = 'Michael Holtzscher'
__email__ = 'mholtz@protonmail.com'
__license__ = 'MIT'
